"""add coluna assinatura_base64 em requisicoes_tecnicos

Revision ID: 1455a4b6179f
Revises: 25715c368a2e
Create Date: 2025-08-19 09:57:48.023966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1455a4b6179f'
down_revision = '25715c368a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisicoes_tecnicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_base64', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisicoes_tecnicos', schema=None) as batch_op:
        batch_op.drop_column('assinatura_base64')

    # ### end Alembic commands ###
