"""add responsavel to estoque

Revision ID: 1ba9d8d0295a
Revises: 7ba5fa62db1e
Create Date: 2025-07-26 20:36:44.057848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba9d8d0295a'
down_revision = '7ba5fa62db1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_estoque_tipo_servico', 'tipo_servico', ['tipo_servico_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.drop_constraint('fk_estoque_tipo_servico', type_='foreignkey')
        batch_op.drop_column('responsavel')

    # ### end Alembic commands ###
