"""Adiciona campo quantidade ao historico de equipamento

Revision ID: 25715c368a2e
Revises: a3a190efd451
Create Date: 2025-08-07 11:10:33.726870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25715c368a2e'
down_revision = 'a3a190efd451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_equipamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_equipamentos', schema=None) as batch_op:
        batch_op.drop_column('quantidade')

    # ### end Alembic commands ###
