"""Campos endereco, bairro e codigo_imovel opcionais na baixa tecnica

Revision ID: 2d49b0e067eb
Revises: 9669d8ac9baf
Create Date: 2025-07-24 14:17:47.779660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d49b0e067eb'
down_revision = '9669d8ac9baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baixas_tecnicas', schema=None) as batch_op:
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baixas_tecnicas', schema=None) as batch_op:
        batch_op.alter_column('endereco',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
