"""add tipo_servico_id with named fk to notas_fiscais_entrada

Revision ID: 4219f4c722bd
Revises: 1ba9d8d0295a
Create Date: 2025-07-26 20:44:17.585449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4219f4c722bd'
down_revision = '1ba9d8d0295a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas_fiscais_entrada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_servico_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_nota_tipo_servico', 'tipo_servico', ['tipo_servico_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas_fiscais_entrada', schema=None) as batch_op:
        batch_op.drop_constraint('fk_nota_tipo_servico', type_='foreignkey')
        batch_op.drop_column('tipo_servico_id')

    # ### end Alembic commands ###
