"""add resp_projeto to requisicoes_tecnicos

Revision ID: 55b5018e69a7
Revises: 9df09742559b
Create Date: 2025-07-26 11:10:39.349137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b5018e69a7'
down_revision = '9df09742559b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisicoes_tecnicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resp_projeto', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisicoes_tecnicos', schema=None) as batch_op:
        batch_op.drop_column('resp_projeto')

    # ### end Alembic commands ###
