"""Add responsavel to TipoServico

Revision ID: 764f7aeaf82a
Revises: 4219f4c722bd
Create Date: 2025-07-26 22:15:30.236460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764f7aeaf82a'
down_revision = '4219f4c722bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_servico', schema=None) as batch_op:
        batch_op.drop_column('responsavel')

    # ### end Alembic commands ###
