"""estrutura inicial

Revision ID: 9669d8ac9baf
Revises: 
Create Date: 2025-07-20 10:55:49.717259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9669d8ac9baf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('tipo_servico', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_fiscais_entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_nf', sa.String(length=50), nullable=False),
    sa.Column('reserva', sa.String(length=50), nullable=True),
    sa.Column('tipo_servico', sa.String(length=100), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('empresa', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipo_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('area_tecnica', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipo_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('transferencias_externas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('autorizado_por', sa.String(length=100), nullable=False),
    sa.Column('retirado_por', sa.String(length=100), nullable=False),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipo_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baixas_tecnicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('codigo_imovel', sa.String(length=100), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipo_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('quantidade_minima', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventarios_tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipo_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kits_iniciais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_kit', sa.String(length=150), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipo_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_fiscais_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_fiscal_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['notas_fiscais_entrada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisicoes_tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_responsavel', sa.String(length=100), nullable=False),
    sa.Column('solicitante_tecnico', sa.String(length=100), nullable=False),
    sa.Column('solicitante_tecnico_id', sa.Integer(), nullable=True),
    sa.Column('tipo_servico', sa.String(length=100), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('observacao_estoque', sa.Text(), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('codigo_imovel', sa.String(length=50), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['solicitante_tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saldo_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('codigo_imovel', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipo_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_acesso_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('transferencias_externas_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transferencia_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['transferencia_id'], ['transferencias_externas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transferencias_internas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('area_tecnica', sa.String(length=100), nullable=False),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipo_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('baixas_tecnicas_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baixa_tecnica_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['baixa_tecnica_id'], ['baixas_tecnicas.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_estoque_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('quantidade_contada', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario_estoque.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventarios_tecnicos_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_contada', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventarios_tecnicos.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kits_iniciais_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_inicial_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['kit_inicial_id'], ['kits_iniciais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisicoes_tecnicos_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisicao_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requisicao_id'], ['requisicoes_tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transferencias_internas_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transferencia_interna_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['transferencia_interna_id'], ['transferencias_internas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transferencias_internas_itens')
    op.drop_table('requisicoes_tecnicos_itens')
    op.drop_table('kits_iniciais_itens')
    op.drop_table('inventarios_tecnicos_itens')
    op.drop_table('inventario_estoque_item')
    op.drop_table('baixas_tecnicas_itens')
    op.drop_table('usuarios')
    op.drop_table('transferencias_internas')
    op.drop_table('transferencias_externas_itens')
    op.drop_table('token_acesso_tecnico')
    op.drop_table('saldo_tecnico')
    op.drop_table('requisicoes_tecnicos')
    op.drop_table('notas_fiscais_itens')
    op.drop_table('kits_iniciais')
    op.drop_table('inventarios_tecnicos')
    op.drop_table('estoque')
    op.drop_table('baixas_tecnicas')
    op.drop_table('transferencias_externas')
    op.drop_table('tecnicos')
    op.drop_table('itens')
    op.drop_table('tipo_servico')
    op.drop_table('notas_fiscais_entrada')
    op.drop_table('inventario_estoque')
    op.drop_table('empresas')
    # ### end Alembic commands ###
