"""Add assinatura_path to requisicoes_tecnicos

Revision ID: 9df09742559b
Revises: 2d49b0e067eb
Create Date: 2025-07-25 09:05:31.420197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df09742559b'
down_revision = '2d49b0e067eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisicoes_tecnicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisicoes_tecnicos', schema=None) as batch_op:
        batch_op.drop_column('assinatura_path')

    # ### end Alembic commands ###
