"""add eh_equipamento to Item

Revision ID: a3a190efd451
Revises: 9f1b9923c065
Create Date: 2025-08-06 09:59:48.469912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a190efd451'
down_revision = '9f1b9923c065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamentos_tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eh_equipamento', sa.Boolean(), nullable=True))

    with op.batch_alter_table('notas_fiscais_entrada', schema=None) as batch_op:
        batch_op.drop_column('total_nota')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas_fiscais_entrada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_nota', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True))

    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.drop_column('eh_equipamento')

    op.drop_table('historico_equipamentos')
    op.drop_table('equipamentos_tecnicos')
    # ### end Alembic commands ###
