"""add assinatura_base64 em TransferenciaExterna

Revision ID: ad493b11a123
Revises: b659a3b9887e
Create Date: 2025-08-22 20:37:39.600547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad493b11a123'
down_revision = 'b659a3b9887e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferencias_externas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_base64', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferencias_externas', schema=None) as batch_op:
        batch_op.drop_column('assinatura_base64')

    # ### end Alembic commands ###
