"""add assinatura_base64 em TransferenciaInterna

Revision ID: b659a3b9887e
Revises: 1455a4b6179f
Create Date: 2025-08-22 15:01:08.326325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b659a3b9887e'
down_revision = '1455a4b6179f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferencias_internas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_base64', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferencias_internas', schema=None) as batch_op:
        batch_op.drop_column('assinatura_base64')

    # ### end Alembic commands ###
